package com.innaval.desafioinchurch.core.exceptions

class ResourceNotFoundException: Exception("Recurso n√£o encontrado")